# Generated by Django 4.2.2 on 2023-07-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tick', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concert',
            new_name='Concerts',
        ),
    ]
